### ISSUE TITLE
UnicodeDecodeError: 'charmap'

### ISSUE THREAD

**Issue by matteoatflow** [awslabs/agent-evaluation#79]
This error was encountered when installing and setting up by cloning the github repository and then executing pip install .
The trace obtained was the following:

PS C:\Users\MatteoVitellaro\Documents\Sandbox\amazon_test\agent-evaluation> pip install .
Processing c:\users\matteovitellaro\documents\sandbox\amazon_test\agent-evaluation
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "C:\Users\MatteoVitellaro\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\MatteoVitellaro\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MatteoVitellaro\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MatteoVitellaro\AppData\Local\Temp\pip-build-env-uy0y5fha\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MatteoVitellaro\AppData\Local\Temp\pip-build-env-uy0y5fha\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\MatteoVitellaro\AppData\Local\Temp\pip-build-env-uy0y5fha\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 33, in <module>
        File "<string>", line 23, in read
        File "C:\Users\MatteoVitellaro\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1916: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by sharonxiaohanli** [comment]
@matteoatflow
I can't reproduce the same issue. Maybe can you try to install it from a virtual environment?

**Comment by sharonxiaohanli** [comment]
Installing locally from virtual environment works fine.
